### ISSUE TITLE
failed to start on port: 5299 Is something else running?

### ISSUE THREAD

**Issue by tsmilam** [linuxserver/docker-lazylibrarian#10]
I kept getting an error that something was already running on port 5299, which was showing up in the output of docker logs. This occurred because I set the value 'http_host' to lazylibrarian.mydomain.com. I tried changing the value of http_host to the address of the host this container was running on, and got the same result.

Then I tried setting http_host = 0.0.0.0, and that fixed it. This might be a better default value.

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

**Comment by HaoZeke** [comment]
This actually is still relevant.

Due to docker not binding to 5299 it gives a wrong redirect.

As shown here:
https://github.com/itsmegb/LazyLibrarian/issues/83

**Comment by thelamer** [comment]
This container simply presents the application to a port, you can bind it server side to whatever you want. 

@tsmilam it sound like you need to bind host side to 80 for your site to work: 

IE: 
```
docker run \
  --name=lazylibrarian \
  -e PGID=1000 -e PUID=1000  \
  -e TZ=US/Pacific \
  -p 80:5299 \
  linuxserver/lazylibrarian
```

@HaoZeke 

Running this container through a reverse proxy will still not cause any redirects. While you are having an issue this does not seem to be the place to ask question about how to properly configure your reverse proxy.

**Comment by rcarmo** [comment]
I am getting this now after the latest upgrade, and there is _nothing_ else running on the machine right now with TCP ports open...

**Comment by thespad** [comment]
Please don't revive 5 year old closed issues, especially not with a "me too" post.

If you have a new issue (even if it has similar symptoms to an old closed one) please open a new issue and fill out the issue template.
