### ISSUE TITLE
Needs CalibreDB

### ISSUE THREAD

**Issue by HaoZeke** [linuxserver/docker-lazylibrarian#12]
# Suggestion

Calibredb is required for integration with calibre, without which this is rather hard to use efficiently..

**Comment by thelamer** [comment]
@HaoZeke I just looked into baking this in and it looks like the dependancies surrounding calibre would require the image to have glibc hacked into it. 

I can tell you from other repos this will most likely not happen in the short term until Alpine has an official solution for this. 

In the mean time there is a container that has what you are looking for: 

https://github.com/Thraxis/docker-lazylibrarian-calibre

**Comment by HaoZeke** [comment]
Thanks for the response and the alternative!
