### ISSUE TITLE
Unable to extract TAR files

### ISSUE THREAD

**Issue by stlouisn** [linuxserver/docker-lazylibrarian#14]
Unhandled exception in processDir: Traceback (most recent call last): File "/app/lazylibrarian/lazylibrarian/postprocess.py", line 489, in processDir res = unpack_archive(os.path.join(pp_path, f), pp_path, matchtitle) File "/app/lazylibrarian/lazylibrarian/postprocess.py", line 240, in unpack_archive z = tarfile.TarFile(pp_path) File "/usr/lib/python2.7/tarfile.py", line 1587, in init self.firstmember = self.next() File "/usr/lib/python2.7/tarfile.py", line 2370, in next raise ReadError(str(e)) ReadError: invalid header

after manually extracting the TAR file, post processing ran correctly.

**Comment by homerr** [comment]
As this is nearly a year old and no further issues have been rasied I deem this to be a temporary error either with an old build, or, the downloaded tar file.

Feel free to re-open if this persists
