### ISSUE TITLE
Fresh Install, Database Errors

### ISSUE THREAD

**Issue by CheckYourSix** [linuxserver/docker-lazylibrarian#16]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

Host OS is CentOS 7 Minimal

The command I used to create:

docker create --name lazylibrarian -p 5299:5299 -e PUID=1000 -e PGID=1000 -e TZ=America/New_York -v /etc/localtime:/etc/localtime:ro -v /home/docker/appdata/lazylibrarian:/config -v /mnt/media/books:/books -v /mnt/media/downloads:/downloads linuxserver/lazylibrarian

Docker log output:

[docker@media ~]$ docker logs lazylibrarian
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing...
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/
Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donations/
-------------------------------------
GID/UID
-------------------------------------
User uid:    1000
User gid:    1000
-------------------------------------
[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
[cont-init.d] 30-config: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Lazylibrarian is starting up...
07-Apr-2018 13:45:03 - INFO :: MAIN : __init__.py:initialize:567 : Log level set to [1]- Log Directory is [/config/log] - Config level is [1]
07-Apr-2018 13:45:03 - INFO :: MAIN : __init__.py:initialize:573 : Screen Log set to INFO
07-Apr-2018 13:45:03 - INFO :: MAIN : __init__.py:config_read:853 : Config file loaded
07-Apr-2018 13:45:03 - INFO :: MAIN : __init__.py:initialize:614 : Database is version 0, integrity check: ok
07-Apr-2018 13:45:04 - INFO :: MAIN : __init__.py:build_bookstrap_themes:1207 : Bookstrap found 16 themes
07-Apr-2018 13:45:04 - INFO :: MAIN : LazyLibrarian.py:main:201 : Starting LazyLibrarian on port: 5299, webroot ""
07-Apr-2018 13:45:04 - INFO :: MAIN : webStart.py:initialize:56 : Starting LazyLibrarian web server on http://0.0.0.0:5299/
07-Apr-2018 13:45:04 - ERROR :: DB_UPGRADE : database.py:action:62 : Database error: near ",": syntax error
07-Apr-2018 13:45:04 - ERROR :: DB_UPGRADE : database.py:action:63 : Failed query: [CREATE TABLE IF NOT EXISTS users (UserID TEXT UNIQUE, UserName TEXT UNIQUE,                                 Password TEXT, Email TEXT, Name TEXT, Perms INTEGER, HaveRead TEXT, ToRead TEXT,                                 CalibreRead TEXT, CalibreToRead TEXT), BookType TEXT]
07-Apr-2018 13:45:04 - ERROR :: DB_UPGRADE : dbupgrade.py:dbupgrade:373 : Unhandled exception in database upgrade: Traceback (most recent call last):
  File "/app/lazylibrarian/lazylibrarian/dbupgrade.py", line 166, in dbupgrade
    CalibreRead TEXT, CalibreToRead TEXT), BookType TEXT')
  File "/app/lazylibrarian/lazylibrarian/database.py", line 46, in action
    sqlResult = self.connection.execute(query)
OperationalError: near ",": syntax error

No symlinks on any volume mounts

This is a brand new container with a brand new directory, no previous data was migrated. I have a user called docker. I made /home/docker/appdata/lazylibrarian. It's owned by docker:docker. UID 1000 and GID 1000. Permissions are standard. SELinux is disabled.

You can see the errors I copied from LazyLibrarian's GUI here: https://pastebin.com/raw/VdRiAruw

##  Thanks, team linuxserver.io

**Comment by tobbenb** [comment]
How did you install docker?

**Comment by CheckYourSix** [comment]
I did it with yum install docker. I've since been informed to follow the Docker guides instead of using the default yum repo for it. But the problem isn't with Docker, it's with LL or the image. I tried it with VMWare's Photon OS and another person on Discord tried setting up LL on his system and everything resulted in the same errors.

**Comment by tobbenb** [comment]
Yes, I saw @sparklyballs mentioned he had the same issue in our Discord chat and that it's a LL issue.

**Comment by philborman** [comment]
There is a typo in the dbupgrade code, extra closing bracket. Will push a fix in the next hour, sorry abut that!

**Comment by sparklyballs** [comment]
@philborman thanks 

and shit happens lol

**Comment by homerr** [comment]
Long sorted - closed 👍
