### ISSUE TITLE
Include ebook-convert for file format conversions

### ISSUE THREAD

**Issue by jesjimher** [linuxserver/docker-lazylibrarian#19]
It would be nice if Docker image included ebook-convert script. It's actually used by some helper scripts inside LazyLibrarian (i. e. example_ebook_convert.py, used by custom notifications), that right now just fail because there's no ebook-convert available.

**Comment by philborman** [comment]
The Thraxis docker includes this, it's part of calibre. See the lazylibrarian homepage for a link.
