### ISSUE TITLE
LazyLibrarian tries to create existing dir/files

### ISSUE THREAD

**Issue by mihaiblaga89** [linuxserver/docker-lazylibrarian#20]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

Ubuntu 16.04

/opt/LazyLibrarian/Logs : Unable to create folder for logs: [Errno 13] Permission denied: '/opt'
  File "/app/lazylibrarian/LazyLibrarian.py", line 166, in main
    lazylibrarian.initialize()
  File "/app/lazylibrarian/lazylibrarian/__init__.py", line 643, in initialize
    logger.lazylibrarian_log.initLogger(loglevel=CONFIG['LOGLEVEL'])
  File "/app/lazylibrarian/lazylibrarian/logger.py", line 49, in initLogger
    backupCount=lazylibrarian.CONFIG['LOGFILES'])
  File "/usr/lib/python2.7/logging/handlers.py", line 117, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python2.7/logging/handlers.py", line 64, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python2.7/logging/__init__.py", line 920, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python2.7/logging/__init__.py", line 950, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 2] No such file or directory: u'/opt/LazyLibrarian/Logs/lazylibrarian.log'

The idea is that I've already had LL working standalone and now I want to move it to docker. I've stopped my instance of LL and pointed /config, /download, /books to the existing folders and I get these kind of errors. Shouldn't it just use already existing ones?

**Comment by philborman** [comment]
You probably have logdir = /opt/LazyLibrarian/Logs/ in your lazylibrarian config.ini file from your previous installation. You should change that to logdir = /config/Logs/ so the path is kept to one docker can access

**Comment by homerr** [comment]
I have not reproduced this error and can therefore presume it is related to what the creator of the application has suggested. Closing, unless further information is provided by the issue creator.
