### ISSUE TITLE
Important Notice

### ISSUE THREAD

**Issue by ghost** [linuxserver/docker-lazylibrarian#21]
See https://github.com/DobyTang/LazyLibrarian/issues/1666

**Comment by homerr** [comment]
Thanks, we'll update this to pull in from their new GitLab home

**Comment by DavidFW1960** [comment]
When will this change request be implemented?

**Comment by Epod** [comment]
@DavidFW1960 & @homerr  - I just did a pull request that fixes this issue. Hopefully it gets approved :)

**Comment by DavidFW1960** [comment]
Hi @Epod great.... I reported an issue to them that has been fixed now however of course until the repo location is updated and the repo is pulled I can't access it.

**Comment by ghost** [comment]
@homerr please review PR, LL is currently broken!

**Comment by DavidFW1960** [comment]
this has still not been addressed in latest image. can the pr be merged?

**Comment by homerr** [comment]
New PR opened for this, just doing final QA on how the container handles upgrading before it goes live. #24

**Comment by homerr** [comment]
All done, pull the latest image and you'll be up to date.

**Comment by DavidFW1960** [comment]
Nice job!!! and the bug I had is now gone as well. Thanks!
