### ISSUE TITLE
image cache not persistent across restarts

### ISSUE THREAD

**Issue by CHBMB** [linuxserver/docker-lazylibrarian#3]
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)](https://linuxserver.io)

From @PhAzE-Variance

Hey,

So the docker is running much better with it being able to save the config files.  One thing though, when the docker is rebooted it loses its image cache so all the book covers and artists images are wiped. Perhaps you can setup so it maps /app/lazylibrarian/data/images/cache somewhere into the /config folder?  

I'm not sure if it's better to map the entire /app/lazylibrarian/data folder or just the cache folder though.  Probably just the image/cache folder as it seems all the other data is stored int eh config folder normally.

-T

**Comment by CHBMB** [comment]
Just looking at this and it's only if the container is updated not restarted, and I think it's been caused by the fix for the config.ini not being persistent.

**Comment by tobbenb** [comment]
Copy files on shutdown, then copy back on startup?
Might be too many images for a big library?
Maybe ask the developer for an option to specify image cache location?

**Comment by CHBMB** [comment]
Or symlink?

**Comment by sparklyballs** [comment]
DobyTang/LazyLibrarian#498

**Comment by sparklyballs** [comment]
The author has made a fix so that images are cached in /config/cache now.
