### ISSUE TITLE
Cover creation for books and mags

### ISSUE THREAD

**Issue by danfozzy** [linuxserver/docker-lazylibrarian#4]
Running this docker on my synology ds415+

Everything is working well with the exception of creating covers for the books/mags. The default is to leave the option blank which will use PythonMagick or Wand interfaces to ImageMagick.

This doesn't produce any covers? Is this docker good for ImageMagick?

**Comment by CHBMB** [comment]
Are you asking if imagemagick is included?  I don't believe it is.

**Comment by danfozzy** [comment]
Is there anyway to include what is required to allow LL to create the covers?

Thanks for your reply

**Comment by CHBMB** [comment]
I'm confused by your original post.  Is it pythonmagick or imagemagick you want included?  It may be possible if there is an Alpine package for it.

**Comment by danfozzy** [comment]
this is what it says in the settings:

Program for creating magazine covers (example: ImageMagick "convert")
Leave blank to use PythonMagick or Wand interfaces to ImageMagick, put None to disable cover creation

@philborman can you shed some light?

**Comment by philborman** [comment]
Documentation is a bit out of step with reality at the moment.  That
setting is used to override the way lazylibrarian creates magazine covers.
It creates a jpeg from the first page of a magazine pdf file when it adds
them to the library, or on a library scan. Doesn't do anything for books.

We try lots of methods to create the covers to cope with different systems
with different installed programs, (eg some Synology NAS systems ship with
a version of ghostscript that doesnt read pdf) and if none of the built in
methods work you can override them. If you don't want lazylibrarian to
create magazine covers, put the word None in the box.

We try...  (not necessarily in this order)
ghostscript - local copy in lazylibrarian root dir, or a copy in your
system path. This is the easiest to use, just install and go.
imagemagick  - we try the Wand and PythonMagick python interfaces to it,
you will need to have them installed system wide probably using pip.

Using the config box...
imagemagick "convert" program - if you don't have the interfaces installed
but still want to use imagemagick you can use the convert program supplied
with imagemagick by putting the path to to it in the box
You can also use the lazylibrarian supplied gsconvert,py in this box to use
ghostscript, though that isn't really necessary any more as the same
facility is built into lazylibrarian itself now.

Hope this makes sense, if not let me know.

**Comment by danfozzy** [comment]
@philborman So just to confirm, with ghostscript installed and the settings box left blank for cover creation it should create the covers automatically

**Comment by philborman** [comment]
Yes,  as long as ghostscript is in your system path

**Comment by danfozzy** [comment]
works a treat, thank you

**Comment by CHBMB** [comment]
@philborman Thanks for the help with this, much appreciated.  Wondered if you'd be interested in mentioning this container as an install option for LazyLibrarian?  We've got this, the x64 version and we also have an [armhf](https://github.com/linuxserver/docker-lazylibrarian-armhf) version.  Both based on Alpine Linux and get updated on a weekly basis to remain current and get upstream fixes.

**Comment by philborman** [comment]
ok, just added those links to my local git repo, will push to master shortly. Just testing some other changes first.
