### ISSUE TITLE
python3 PIL (Pillow) library dependancy

### ISSUE THREAD

**Issue by rupaschomaker** [linuxserver/docker-lazylibrarian#40]
As of commit:
https://gitlab.com/LazyLibrarian/LazyLibrarian/commit/b7b58e267ca9812da53b14cb6fab29137fa38eb6

lazylibrarian added support for PIL (Pillow) for thumbnail generation of magazines...  Would be nice if the docker image included PIL as well.

**Comment by aptalca** [comment]
Thanks for the heads up
