### ISSUE TITLE
lazy librarian not starting after docker update, needs a colon at line 1070 of postprocess.py

### ISSUE THREAD

**Issue by zombiehoffa** [linuxserver/docker-lazylibrarian#44]
https://gitlab.com/LazyLibrarian/LazyLibrarian/issues/2060

after the docker image update I get the problem outlined in the lazylibrarian  gitlab issue tracker above. Fix is really easy, just needs a colon on the end of line 1070 of postprocess.py

**Comment by j0nnymoe** [comment]
This is an upstream fix. Once this has been done, our container will pickup the update.
