### ISSUE TITLE
Feature request: FFMPEG capabilities

### ISSUE THREAD

**Issue by madknave** [linuxserver/docker-lazylibrarian#45]
Commit https://gitlab.com/LazyLibrarian/LazyLibrarian/-/commit/fda2b28162ff659deb5dc87c323f2c68a2adf65b introduced the possibility of pre-processing audio files within the lazylibrary software, for this to happen FFMPEG capabilities are required in the container.

This request is to add FFMPEG to the container.

Cheers!

**Comment by aptalca** [comment]
This would be a good candidate for a docker mod: https://blog.linuxserver.io/2019/09/14/customizing-our-containers/#docker-mods
and https://github.com/linuxserver/docker-mods

**Comment by mKeRix** [comment]
I create a Docker mod that makes ffmpeg available to the lazylibrarian container and published it to [Docker Hub](https://hub.docker.com/repository/docker/mkerix/docker-ffmpeg-mod). You can find the matching repository [here](https://github.com/mKeRix/docker-ffmpeg-mod).

Enabling it is as easy as adding `mkerix/docker-ffmpeg-mod:latest` to your `DOCKER_MODS` env variable.

**Comment by CHBMB** [comment]
@mKeRix Want to submit a PR to our docker-mods repo so it appears on our listing and then submit a PR here for the documentation?
