### ISSUE TITLE
Properly set `HOME` for launched services

### ISSUE THREAD

**Issue by brianredbeard** [linuxserver/docker-lazylibrarian#54]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

## Expected Behavior
As a part of dropping privileges through the use of `s6` the user environment should utilize the value of `HOME` from  GNU Name Service Switch for the effective user.

## Current Behavior
Presently the LazyLibrarian service is launched in a way which does not mutate the `HOME` environment variable.  As a result it inherits the value `HOME=/root` which causes a number of secondary issues, like those in #31.

e.g. :

```
~# ps fauxwww | grep -i lazy
root     21836  0.0  0.0   5856   696 pts/27   S+   14:32   0:00          \_ grep --color=auto -i lazy
root     23153  0.0  0.0    184     4 pts/0    S+   14:01   0:00  |           \_ s6-supervise lazylibrarian
1002     23158  0.5  0.7 1172224 127664 ?      Ssl  14:01   0:09  |               \_ python3 /app/lazylibrarian/LazyLibrarian.py --datadir /config --nolaunch
~# xargs --null --max-args 1 echo < /proc/23158/environ 
LANG=en_US.UTF-8
TZ=Etc/UTC
HOSTNAME=e8e31ddab758
PUID=1002
PGID=1002
PWD=/run/s6/services/lazylibrarian
HOME=/root
TERM=xterm
SHLVL=0
CWD=/
LANGUAGE=en_US.UTF-8
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

As child processes are spawned, they inherit the values from the parent.  This was discovered via the following log messages (after pressing the "Test calibredb" button in "Settings" -> "Processing"):

```
calibredb res 90[No write acces to /root/.config/calibre using a temporary dir instead Added book ids: 130 ]
```

Further introspection shows that, upon execution of the `calibredb` binary, the following configuration structure is created:

```
${HOME}/.config/
${HOME}/.config/calibre
${HOME}/.config/calibre/global.py.json
${HOME}/.config/calibre/plugins
```

As the value of `${HOME}` is `/root`, the user specified by PUID/GUID does not have execution permission and cannot traverse into `/root` even if the requisite permissions exist upon child path components.

When the process is run from a login shell (thus setting `HOME` to the proper value) the correct path is chosen.  This is validated by tracing the child bash process for `stat()` syscalls and running `calibredb` from the spawned shell:

```
~# strace -feprocess -eopen -e stat -p 5141 2>&1 | grep -v ENOENT | grep \/config\/\.config 
[pid 10052] stat("/config/.config", {st_mode=S_IFDIR|0755, st_size=14, ...}) = 0
[pid 10052] stat("/config/.config/calibre", {st_mode=S_IFDIR|0755, st_size=42, ...}) = 0
[pid 10052] stat("/config/.config/calibre/global.py.json", {st_mode=S_IFREG|0755, st_size=1044, ...}) = 0
[pid 10052] stat("/config/.config/calibre/plugins", {st_mode=S_IFDIR|0755, st_size=0, ...}) = 0
```

## Environment
**OS:** Linux
**CPU architecture:** x86_64

**Comment by aptalca** [comment]
Thanks for the report. Can you do me a favor and test those conditions after recreating the container and setting an env var `HOME=/config`?

Also see if it causes any unwanted side effects.

If it all looks good, we'll set it in the dockerfiles to make it default

**Comment by brianredbeard** [comment]
I can tell you without even testing that (based on years of experience at CoreOS) that taking that action will more than likely have many unintended consequences.  For example: when processes are run as root they're likely to mutate the permissions on whatever directory is specified by `HOME`. Forcing this in the `Dockerfile` is bound to break other components of the base image.

**Comment by tobbenb** [comment]
We do set HOME to /config in a number of images without any issues, so could you at least please try it?
