### ISSUE TITLE
Add build time to docker tags

### ISSUE THREAD

**Issue by kruton** [linuxserver/docker-lazylibrarian#58]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior

Docker tags should contain something sortable like number of seconds since epoch (e.g., date +"%s")

## Current Behavior

Docker tags are based on truncated git commitish with build number attached which is not sortable

## Alternatives Considered

Other projects base their tags on upstream versioning, but lazylibrarian doesn't do that

**Comment by homerr** [comment]
How we tag containers is standard across the entire organisation, a combination of referencing releases/commits, our own internal release and with the build date/time also tagged into the images we produce;

```
            "Labels": {
                "build_version": "Linuxserver.io version:- d24e8fe4-ls34 Build-date:- 2021-08-06T16:13:40+02:00",
                "maintainer": "chbmb",
                "org.opencontainers.image.authors": "linuxserver.io",
                "org.opencontainers.image.created": "2021-08-06T16:13:40+02:00",
```

You should be able to pull everything you need out of there, the commit references the last push to master by the lazylibrarian maintainers and the build date references when we captured it and built it - also referenced in it's own label.
