### ISSUE TITLE
[FEAT]  Requirements from pyproject.toml

### ISSUE THREAD

**Issue by philborman** [linuxserver/docker-lazylibrarian#64]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Do you support installing requirements from pyproject.toml when you build the docker image?
If so, there are several bundled libraries that I would like to remove from source.
Thanks.

### Reason for change

Upgrade, changes to distribution of sources

### Proposed code change

use pyproject.toml in the build process

**Comment by thespad** [comment]
The linked PR is installing from the pyproject.toml, just need to make sure it's happy on arm as we many need to add some extra deps there.

**Comment by philborman** [comment]
Great thanks. The pyproject file works on raspberry pi so should be fine

**Comment by philborman** [comment]
Thanks for the fast response 😉
