### ISSUE TITLE
SyntaxWarning: invalid escape sequence '\ '

### ISSUE THREAD

**Issue by romquenin** [linuxserver/docker-lazylibrarian#79]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I receive this SyntaxWarning message in the log:

`/app/lazylibrarian/cherrypy/process/servers.py:1: SyntaxWarning: invalid escape sequence '\ '`

### Steps To Reproduce

Just want to know why i receive this message and maybe fix it

### Environment

```markdown
- OS: Synology
- How docker service was installed: docker compose
```

### CPU architecture

x86-64

### Docker creation

```bash
lazylibrarian:
    image: linuxserver/lazylibrarian
    ports:
    - 5299:5299
    container_name: lazylibrarian
    environment:
    - PGID=100
    - PUID=1026
    - TZ=Europe/Paris
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "10m"
    restart: unless-stopped
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /volume1/docker/lazylibrarian:/config
    - /volume1/docker/shared:/shared
    - /volume1/downloads:/data
    - /volume1/downloads:/downloads
    - /volume1/ebook/AUDIOBOOK:/audiobooks
    - /volume1/ebook:/books    
    networks:
      - default
```

### Container logs

```bash
/app/lazylibrarian/cherrypy/process/servers.py:1: SyntaxWarning: invalid escape sequence '\ '
```

**Comment by skuid87** [comment]
Any updates on this? I'm having the exact same issue. Installed via docker compose too.

**Comment by thespad** [comment]
It's just a warning. Python 3.12 started surfacing them to try and force developers to fix the issues as they were just ignoring them.
